---
- name: Join Master Members
  hosts: member
  become: true
  gather_facts: true
  tasks:
    - name: Generated token - 1.
      local_action: shell sed -n 70,73p ./token > ./mastertoken
    - name: Copy master token
      copy:
        src: ./mastertoken
        dest: /tmp/join-command.sh
        owner: root
        group: root
        mode: '0777'
    - name: Generated token - 2.
      shell: sed -i 's/\b:80\b/& --apiserver-advertise-address {{ ansible_all_ipv4_addresses | ipaddr('10.64.246.0/23') | first }} --ignore-preflight-errors=NumCPU/' /tmp/join-command.sh
    - name: Add new Kubernetes master member
      command: sh /tmp/join-command.sh
    - name: Create .kube directory
      become: yes
      become_user: azure
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/azure/.kube/config
        remote_src: yes
        owner: azure
